frequency: 30
two_d_mode: true

odom0: /odom
odom0_config: [false,  false,  false, # ttf
               false, false, false,
               true,  true,  false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_relative: false
odom0_pose_rejection_threshold: 99999
odom0_twist_rejection_threshold: 99999

imu0: /imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: false
imu0_remove_gravitational_acceleration: true

# process_noise_covariance: [0.1, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0.1]

base_link_frame: base_link
odom_frame: odom
world_frame: odom

transform_timeout: 0.5

transform_time_offset: 0.0
predict_to_current_time: false
publish_tf: true
