TebLocalPlannerROS:
  # ======== 기본 설정 ========
  odom_topic: odometry/filtered
  map_frame: map           

  # ======== 로봇 사양 (안정성을 위해 보수적으로 설정) ========
  # 선속도 대비 각속도를 낮춰 지그재그 현상 방지
  max_vel_x: 0.3
  max_vel_x_backwards: 0.1
  max_vel_theta: 0.3           # max_vel_x에 비해 너무 크지 않게 설정하는 것
  acc_lim_x: 0.5
  acc_lim_theta: 0.2
 
  # 차동 구동 로봇의 경우 0.0, Ackerman 방식의 경우 실제 최소 회전 반경 입력
  min_turning_radius: 0.0

  # 로봇의 실제 발자국(footprint) 설정 (매우 중요)
  # 아래는 예시이며, 실제 로봇의 크기에 맞게 꼭 수정해주세요.
  footprint_model:
    type: "polygon"
    vertices: [[0.320, 0.255], [0.320, -0.255], [-0.320, -0.255], [-0.320, 0.255]]
 
  # ======== 궤적 설정 (Trajectory) ========
  teb_autosize: true
  dt_ref: 0.4                 # 경로의 시간 해상도. 0.3 ~ 0.6 사이에서 시작 0.4
  global_plan_prune_distance: 2.0 # 1.0
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 15.0
  exact_arc_length: true
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true # Global plan의 방향을 우선
  max_global_plan_lookahead_dist: 6.0 # 3.0
  feasibility_check_no_poses: 4 # 경로 중 몇개가 실행 가능해야 움직이는지 10
  global_plan_viapoint_sep: 0.3
 

  # ======== 목표점 도달 허용 오차 (Goal Tolerance) ========
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.2 #0.25 -> 14.3도, 0.3 -> 17.2도, 0.2 -> 11.4도
  free_goal_vel: false

  # ======== 장애물 설정 (Obstacles) ========
  min_obstacle_dist: 0.25         # 로봇과 장애물 사이의 최소 이격 거리  0.2 0.15 111111111111111111111111111111111111111
  inflation_dist: 0.50
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.5
  obstacle_poses_affected: 20        # 경로 Sample 개수

  # ======== 최적화 가중치 (Weights) - 안정성에 가장 중요한 부분 ========
  # 여러 목표간의 균형을 맞춘 설정
  optimization_activate: true
  no_inner_iterations: 5
  no_outer_iterations: 4
 
  weight_optimaltime: 1.0      # 경로의 전체 소요 시간을 최적화 (기본 목표)
  weight_kinematics_nh: 1000.0   # 로봇의 기구학적 제약을 반드시 따르도록 함 (매우 중요)
  weight_kinematics_forward_drive: 400.0 # 후진을 억제하고 전진을 유도 2000.0
  #penalty_epsilon: 0.2 # 기본값은 0.1

 
  # 아래 값들은 너무 높으면 진동의 원인이 될 수 있음
  weight_shortest_path: 0.5    # 경로를 직선에 가깝게 만들려는 힘. 우선은 낮은 값으로 시작
  weight_obstacle: 50        # 장애물을 얼마나 강하게 회피할지 50.0
 
  # 속도 및 가속도 한계 초과 페널티
  weight_max_vel_x: 2.0
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
 
  # 사용하지 않는 가중치는 0.0으로 설정
  weight_kinematics_turning_radius: 0.0
  weight_viapoint: 30.0

  # ======== 고급 장애물 회피 (Homotopy Class Planning) ========
  # 다중 경로 계획 기능 활성화
  enable_homotopy_class_planning: false
  enable_multithreading: true
  max_number_classes: 4
 
GlobalPlanner:
  allow_unknown: false         # 미탐색 영역도 경로 통과 허용
  default_tolerance: 0.2       # 근처에 장애물이 있어도 0.3m 이내면 통과 허용
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false
  lethal_cost: 253
  neutral_cost: 65
  cost_factor: 10.0 #기존 3.0
