frame_id: map
waypoints:
  - name: p1 # 1층 패널
    x: 1.601
    y: -21.583
    yaw_deg: 124.6
    mission: 3
    slow_zone: false
    aruco_on: false
    wait_key: false

  - name: p2 # 3층 도착지
    x: 0.559
    y: 0.061
    yaw_deg: 178.6
    mission: 2
    slow_zone: false
    aruco_on: false
    wait_key: false
    
    
    
frame_id: map
waypoints:
- name: p1
  x: 2.455
  y: -19.793
  yaw_deg: 164.4
  slow_zone: false
  aruco_on: false
  wait_key: false
