frame_id: map
waypoints:
  - name: p1 # 1층
    x: 0.433
    y: -19.778
    yaw_deg: 179.5
    mission: 3
    slow_zone: false
    aruco_on: false
    wait_key: false

  - name: p2 # 3층
    x: 0.559
    y: 0.061
    yaw_deg: 178.6
    mission: 2
    slow_zone: false
    aruco_on: false
    wait_key: false
