frame_id: map
waypoints:
  - name: p1 # 1층 패널
    x: 1.355
    y: -19.992
    yaw_deg: 152.6
    mission: 3
    slow_zone: false
    aruco_on: false
    wait_key: false
    
  - name: p2 # 1층 엘베 앞
    x: 0.437
    y: -19.86
    yaw_deg: 180.0
    mission: 3
    slow_zone: false
    aruco_on: false
    wait_key: false

  - name: p3 # 3층 도착지
    x: 0.559
    y: 0.061
    yaw_deg: 178.6
    mission: 1
    slow_zone: false
    aruco_on: false
    wait_key: false
