frame_id: map
waypoints:
- name: p1
  x: 5.359
  y: -16.189
  yaw_deg: -170.1
  mission: 3
  slow_zone: false
  aruco_on: false
  wait_key: false
- name: p2
  x: 0.162
  y: 0.18
  yaw_deg: 177.0
  mission: 2
  slow_zone: false
  aruco_on: false
  wait_key: false
